### ISSUE TITLE
module 'ascii_magic' has no attribute 'modes'

### ISSUE THREAD

**Issue by KorewaKiyo** [daernsinstantfortress/WeConnect-Cupra-python#2]
As title says, module is unusable because of the import error.
```
>>> from weconnect_cupra import weconnect_cupra
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/liam/.local/lib/python3.11/site-packages/weconnect_cupra/weconnect_cupra.py", line 8, in <module>
    from weconnect_cupra.auth.openid_session import OpenIDSession
  File "/home/liam/.local/lib/python3.11/site-packages/weconnect_cupra/auth/openid_session.py", line 16, in <module>
    from weconnect_cupra.errors import AuthentificationError, RetrievalError
  File "/home/liam/.local/lib/python3.11/site-packages/weconnect_cupra/errors.py", line 6, in <module>
    from weconnect_cupra.addressable import AddressableLeaf, AddressableObject, AddressableDict
  File "/home/liam/.local/lib/python3.11/site-packages/weconnect_cupra/addressable.py", line 10, in <module>
    from weconnect_cupra.util import toBool, imgToASCIIArt, robustTimeParse, ExtendedWithNullEncoder
  File "/home/liam/.local/lib/python3.11/site-packages/weconnect_cupra/util.py", line 35, in <module>
    def imgToASCIIArt(img: Image, columns: int = 0, mode: ascii_magic.Modes = ascii_magic.Modes.TERMINAL) -> str:
                                                                              ^^^^^^^^^^^^^^^^^
AttributeError: module 'ascii_magic' has no attribute 'Modes'
```

Example files don't function either.

The Modes class stopped being exported in ascii_magic in a commit from Feb 18th, not sure if it was supposed to be added back.
https://github.com/LeandroBarone/python-ascii_magic/commit/ef807a39e28715dfaa30ce052b1a3fda3647b3cb#diff-65fcd22455c54dee4fc5631eab04206e2495215e55e38554d79c987040f4f69d

**Comment by daernsinstantfortress** [comment]
You would need to install with `pip3 install weconnect-cupra-daern[Images]` to use standalone. The default configuration fails to install in Home Assistant otherwise, which is the primary reason this exists.

Regarding the example files, they probably need some love, but at least `access_status.py` should work OK:

`python3 examples/access_status.py -u <username> -p <password> --vin <vehicle_vin> --service MyCupra`

**Comment by KorewaKiyo** [comment]
Turns out I was being a bit dim yesterday when trying to install the standalone, ZSH was trying to run some matching on the brackets, and I wasn't reading the error, sorry!
